### ISSUE TITLE
New Norminette rules

### ISSUE THREAD

**Issue by srgbl** [ApishevAskhad/corewar#26]
It seems Norme has changed.
I got new error when scan project folder including libft and ft_printf libraries:
**define must be a constant value** 

So now we can't define simple macros like:
`define SIZE (MEM_SIZE / 8)`
And can't even define alias for shorten type name:
`define UL unsigned long`
 
It also gives error in ft_printf project because of using **wchar_t** type.

Could you please check this on your machine and using 21-school norminette. I used 42-school norminette and I hope it may gives different output.

**Comment by ApishevAskhad** [comment]
I recommend you to start using 21-school norminette because `Norme: includes/op.h`

**Comment by srgbl** [comment]
Ok. That’s the good news!
